define({
    "Title": "Title",
    "Inbox": "Inbox",
    "Executing": "Em Execução",
    "Sent": "Enviados",
    "Completed": "Completados",
    "Complete": "Completado",
    "State": "Estado",
    "Subject": "Sujeito",
    "Initiator": "Remetente",
    "Executor": "Executor",
    "Creation": "Criação",
    "Actions": "Acções",
    "Data Objects": "Dados",
    "Insert your comment here": "Inserir comentário...",
    "Comment": "Comentar",
    "Create Sub-Request": "Criar Sub-Pedido",
    "Add New Data Object": "Adicionar Novo Objecto de Dados",
    "Sub-Requests": "Sub-Pedidos",
    "Pending Sub-Requests": "Sub-Pedidos Pendentes",
    "Edit Profile": "Editar Perfil",
    "Logout": "Sair",
    "Forward Request": "Reencaminhar Pedido",
    "Forward": "Reencaminhar",
    "Reply": "Responder",
    "Create New Process": "Criar Novo Processo",
    "Process Title": "Título do Processo",
    "Description": "Descrição",
    "List Processes": "Listar Processos",
    "Claim Request": "Aceitar Pedido",
    "Claim": "Aceitar",
    "No inbox requests found": "Não existem novos pedidos na sua inbox",
    "No executing requests found": "Não existem pedido em execução",
    "No sent requests found": "Ainda não enviou nenhum pedido",
    "No completed requests found": "Não existem pedidos completados",
    "No completed processes found": "Não existem processos completados",
    "No ongoing processes found": "Não existem processos a decorrer",
    "No one yet": "Não tem",
    "Cancel": "Cancelar",
    "Unclaimed": "Pendente",
    "Completion": "Completado",
    "Duration": "Duração",
    "Email address": "Endereço de Email",
    "Password": "Password",
    "Sign in": "Entrar",
    "Edit Profile": "Editar Perfil",
    "Name": "Nome",
    "Email": "Email",
    "First and Last name": "Primeiro e Último nome",
    "Save Changes": "Guardar Alterações",
    "Respond to Request": "Responder ao Pedido",
    "Respond": "Responder",
    "Recommendations": "Recomendações",
    "Custom": "Personalizado",
    "Send Request": "Enviar Pedido",
    "Request Subject": "Assunto do Pedido",
    "Ongoing": "Em Execução",
    "Update Data Object": "Actualizar Objecto de Dados",
    "Edit Data Object": "Editar Objecto de Dados",
    "Warning": "Atenção",
    "Error": "Erro",
    "Info": "Informação",
    "Login successful": "Login efectuado com sucesso",
    "Logout successful": "Logout efectuado com sucesso",
    "You must provide at least a title": "Tem de indicar no mínimo um título",
    "The name cannot be empty": "Tem de indicar um nome",
    "The email cannot be empty": "Tem de indicar um email válido",
    "Email and password cannot be empty": "Email e password não podem ser vazios",
    "You must write something in the comment": "Tem de escreve algum texto no comentário",
    "Create Data Object": "Criar Objecto de Dados",
    "Request Labels": "Nomes de Pedidos",
    "Data Labels": "Nomes dos Dados",
    "File": "Ficheiro",
    "Text": "Texto",
    "Label": "Nome",
    "Value": "Valor",
    "Participants": "Participantes",
    "Owner": "Criador",
    "Request claimed successfully": "Pedido aceite com sucesso",
    "Number of Executing Requests": "Número de Pedidos em Execução",
    "Number of Completed Requests": "Número de Pedidos Completados",
    "Statistics": "Estatísticas",
    "Data object copied successfully": "Dado copiado com sucesso",
    "Sub-request canceled successfully": "Sub-pedido cancelado com sucesso",
    "cannot.claim.own.requests": "Não pode aceitar pedidos que iniciou",
    "cannot.reply.with.data.objects.you.didnt.create": "Não pode responder com dados que não criou",
    "expired.auth.token": "O token de autorização expirou. Faça login",
    "invalid.credentials": "Credenciais incorrectas",
    "data.object.already.provided.as.input": "O objecto de dados já foi fornecido no pedido"
});
