define({
    "root": {
        "Title": "Title",
        "Inbox": "Inbox",
        "Executing": "Executing",
        "Sent": "Sent",
        "Completed": "Completed",
        "Complete": "Complete",
        "State": "State",
        "Subject": "Subject",
        "Initiator": "Initiator",
        "Executor": "Executor",
        "Creation": "Creation",
        "Actions": "Actions",
        "Data Objects": "Data Objects",
        "Insert your comment here": "Insert your comment here...",
        "Comment": "Comment",
        "Create Sub-Request": "Create Sub-Request",
        "Add New Data Object": "Add New Data Object",
        "Sub-Requests": "Sub-Requests",
        "Pending Sub-Requests": "Pending Sub-Requests",
        "Edit Profile": "Edit Profile",
        "Logout": "Logout",
        "Forward Request": "Forward Request",
        "Forward": "Forward",
        "Reply": "Reply",
        "Create New Process": "Create New Process",
        "Process Title": "Process Title",
        "Description": "Description",
        "List Processes": "List Processes",
        "Claim Request": "Claim Request",
        "Claim": "Claim",
        "No inbox requests found": "No inbox requests found",
        "No executing requests found": "No executing requests found",
        "No completed requests found": "No completed requests found",
        "No sent requests found": "No sent requests found",
        "No completed processes found": "No completed processes found",
        "No ongoing processes found": "No ongoing processes found",
        "No one yet": "No one yet",
        "Cancel": "Cancel",
        "Unclaimed": "Unclaimed",
        "Completion": "Completion",
        "Duration": "Duration",
        "Email address": "Email address",
        "Password": "Password",
        "Sign in": "Sign in",
        "Edit Profile": "Edit Profile",
        "Name": "Name",
        "Email": "Email",
        "First and Last name": "First and Last name",
        "Save Changes": "Save Changes",
        "Respond to Request": "Respond to Request",
        "Respond": "Respond",
        "Recommendations": "Recommendations",
        "Custom": "Custom",
        "Send Request": "Send Request",
        "Request Subject": "Assunto do Pedido",
        "Ongoing": "Ongoing",
        "Update Data Object": "Update Data Object",
        "Edit Data Object": "Edit Data Object",
        "Warning": "Warning",
        "Error": "Error",
        "Info": "Information",
        "Login successful": "Login successful",
        "Logout successful": "Logout successful",
        "You must provide at least a title": "You must provide at least a title",
        "The name cannot be empty": "The name cannot be empty",
        "The email cannot be empty": "The email cannot be empty",
        "Email and password cannot be empty": "Email and password cannot be empty",
        "You must write something in the comment": "You must write something in the comment",
        "Create Data Object": "Create Data Object",
        "Request Labels": "Request Labels",
        "Data Labels": "Data Labels",
        "File": "File",
        "Text": "Text",
        "Label": "Label",
        "Value": "Value",
        "Participants": "Participants",
        "Owner": "Owner",
        "Request claimed successfully": "Request claimed successfully",
        "Number of Executing Requests": "Number of Executing Requests",
        "Number of Completed Requests": "Number of Completed Requests",
        "Statistics": "Statistics",
        "Data object copied successfully": "Data object copied successfully",
        "Sub-request canceled successfully": "Sub-request canceled successfully",
        "cannot.claim.own.requests": "You may not claim requests initiated by yourself",
        "cannot.reply.with.data.objects.you.didnt.create": "You cannot reply with data objects that you didn't create",
        "expired.auth.token": "Expired Auth Token",
        "invalid.credentials": "Wrong credentials",
        "data.object.already.provided.as.input": "The selected data object is already provided as input"
    },
    "pt-pt": true
});
